"""Fix association table

Revision ID: 48144aafa96f
Revises: ce0554feda31
Create Date: 2025-05-17 11:45:06.436590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48144aafa96f'
down_revision = 'ce0554feda31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 